### ISSUE TITLE
Client manual installation version outdated.

### ISSUE THREAD

**Issue by Sgtlog123** [DanielWillett/DevkitServer#32]
Server install using launcher. v0.0.14.1
Client using Manual installation. v0.0.11.0
![image](https://github.com/DanielWillett/DevkitServer/assets/111060879/27d4da40-2c0e-4641-a92a-1752595754d4)

**Comment by Sgtlog123** [comment]
Unaffected by using launcher.

**Comment by DanielWillett** [comment]
Yeah something broke with the launcher after the new unity version, ill upload the fix soonish.

**Comment by DanielWillett** [comment]
Should be fixed with 
https://github.com/DanielWillett/DevkitServer/releases/tag/0.0.17
